# Permalinks
permalink:        /:title/

# Setup
title:            JEFF LALIC
tagline:          'Web Developer currently residing in Portland'
description:      "Web Developer"
url:              jefflalic.com
baseurl:          "/"

author:
  name:           'Jeff Lalic'
  url:            https://github.com/jlalic/

# Serving
detach: false
port: 9001
host: 127.0.0.1

github:           https://github.com/jlalic/
linkedin:         https://www.linkedin.com/in/jefflalic
